### Variables
@port = 3000

@id = 66428160575fd8e4917b0e48

### FOODS (Menu) Endpoints ###
### Get Food

GET http://localhost:{{port}}/api/Food

### Create new Food
POST http://localhost:{{port}}/api/Food
Content-Type: application/json

{
    "name": "New Food",
    "description": "New Food",
    "price": "New Food"
}

### Update a Food
PUT http://localhost:{{port}}/api/Food/{{id}}
Content-Type: application/json

{
    "name": "Food Update",
    "description": "Food Update",
    "price": "Food Update"
}

### Delete a Food
DELETE http://localhost:{{port}}/api/Food/{{id}}


### EVENTS Endpoints ###
### Get Events show only id and name
GET http://localhost:{{port}}/api/Events

### Get Events show only id and name
GET http://localhost:{{port}}/api/Events/{{id}}

### Create new Events
POST http://localhost:{{port}}/api/Events
Content-Type: application/json

{
    "name": "New Event",
    "location": "New Event",
    "dates": "New Event",
    "hours": "New Event"
}

### Update Events
PUT http://localhost:{{port}}/api/Events/{{id}}
Content-Type: application/json

{
    "name": "Event Update",
    "location": "Event Update",
    "dates": "Event Update",
    "hours": "Event Update"
}

### Delete a Events
DELETE http://localhost:{{port}}/api/Events/{{id}}