### Variables
@port = 3000

@id = 664394f4e3565dce82e9ef20

### FOODS (Menu) Endpoints ###
### Get Food

GET http://localhost:{{port}}/api/Food

### Create new Food
POST http://localhost:{{port}}/api/Food

### Update a Food
PUT http://localhost:{{port}}/api/Food/{{id}}

### Delete a Food
DELETE http://localhost:{{port}}/api/Food/{{id}}


### EVENTS Endpoints ###
### Get Events show only id and name
GET http://localhost:{{port}}/api/Events

### Get Events show only id and details of id
GET http://localhost:{{port}}/api/Events/{{id}}

### Create new Events
POST http://localhost:{{port}}/api/Events

### Update Events
PUT http://localhost:{{port}}/api/Events/{{id}}

### Delete a Events
DELETE http://localhost:{{port}}/api/Events/{{id}}